version: '2'
services:
  web:
    build: .
    links:
      - redis
    ports:
      - 80:3000
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    external: true
